language: python
python:
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "apt-get install -y libacl1-dev"
  - "pip install --use-mirrors Cython"
  - "pip install -e ."
# command to run tests
script: fakeroot -u python -m attic.testsuite.run -vb
