sudo: required

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - python: 3.2
          os: linux
          env: TOXENV=py32
        - python: 3.3
          os: linux
          env: TOXENV=py33
        - python: 3.4
          os: linux
          env: TOXENV=py34
        - language: generic
          os: osx
          osx_image: beta-xcode6.3
          env: TOXENV=py32
        - language: generic
          os: osx
          osx_image: beta-xcode6.3
          env: TOXENV=py33
        - language: generic
          os: osx
          osx_image: beta-xcode6.3
          env: TOXENV=py34

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            - "irc.freenode.org#borgbackup"
        use_notice: true
        skip_join: true
